server:
  port: 8088  # 端口号
  servlet:
    context-path: '/springboot'  #项目访问路径

spring:
  datasource: # 数据源
    username: root
    password: 123@qwe
    url: jdbc:mysql://localhost:3306/homestay?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    encoding: UTF-8
  resources: # 静态资源路径
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

  thymeleaf:
    cache: false  # 使用模板缓存
    suffix: .html
    encoding: UTF-8
    prefix: classpath:/templates/
    mode: HTML5
