package com.aaa.entity;

import java.io.Serializable;

public class Pay implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.p_name
     *
     * @mbg.generated
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.p_number
     *
     * @mbg.generated
     */
    private String pNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.cli_id
     *
     * @mbg.generated
     */
    private Integer cliId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated
     */
    public Pay(Integer pId, String pName, String pNumber, Integer cliId) {
        this.pId = pId;
        this.pName = pName;
        this.pNumber = pNumber;
        this.cliId = cliId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated
     */
    public Pay() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.p_id
     *
     * @return the value of pay.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.p_id
     *
     * @param pId the value for pay.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.p_name
     *
     * @return the value of pay.p_name
     *
     * @mbg.generated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.p_name
     *
     * @param pName the value for pay.p_name
     *
     * @mbg.generated
     */
    public void setpName(String pName) {
        this.pName = pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.p_number
     *
     * @return the value of pay.p_number
     *
     * @mbg.generated
     */
    public String getpNumber() {
        return pNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.p_number
     *
     * @param pNumber the value for pay.p_number
     *
     * @mbg.generated
     */
    public void setpNumber(String pNumber) {
        this.pNumber = pNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.cli_id
     *
     * @return the value of pay.cli_id
     *
     * @mbg.generated
     */
    public Integer getCliId() {
        return cliId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.cli_id
     *
     * @param cliId the value for pay.cli_id
     *
     * @mbg.generated
     */
    public void setCliId(Integer cliId) {
        this.cliId = cliId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pId=").append(pId);
        sb.append(", pName=").append(pName);
        sb.append(", pNumber=").append(pNumber);
        sb.append(", cliId=").append(cliId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}