package com.aaa.entity;

import java.io.Serializable;
import java.util.Date;

public class Water implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water.wat_id
     *
     * @mbg.generated
     */
    private Integer watId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water.wat_money
     *
     * @mbg.generated
     */
    private Integer watMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water.wat_date
     *
     * @mbg.generated
     */
    private Date watDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water.or_id
     *
     * @mbg.generated
     */
    private Integer orId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water.wat_state
     *
     * @mbg.generated
     */
    private Integer watState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table water
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water
     *
     * @mbg.generated
     */
    public Water(Integer watId, Integer watMoney, Date watDate, Integer orId, Integer watState) {
        this.watId = watId;
        this.watMoney = watMoney;
        this.watDate = watDate;
        this.orId = orId;
        this.watState = watState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water
     *
     * @mbg.generated
     */
    public Water() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water.wat_id
     *
     * @return the value of water.wat_id
     *
     * @mbg.generated
     */
    public Integer getWatId() {
        return watId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water.wat_id
     *
     * @param watId the value for water.wat_id
     *
     * @mbg.generated
     */
    public void setWatId(Integer watId) {
        this.watId = watId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water.wat_money
     *
     * @return the value of water.wat_money
     *
     * @mbg.generated
     */
    public Integer getWatMoney() {
        return watMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water.wat_money
     *
     * @param watMoney the value for water.wat_money
     *
     * @mbg.generated
     */
    public void setWatMoney(Integer watMoney) {
        this.watMoney = watMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water.wat_date
     *
     * @return the value of water.wat_date
     *
     * @mbg.generated
     */
    public Date getWatDate() {
        return watDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water.wat_date
     *
     * @param watDate the value for water.wat_date
     *
     * @mbg.generated
     */
    public void setWatDate(Date watDate) {
        this.watDate = watDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water.or_id
     *
     * @return the value of water.or_id
     *
     * @mbg.generated
     */
    public Integer getOrId() {
        return orId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water.or_id
     *
     * @param orId the value for water.or_id
     *
     * @mbg.generated
     */
    public void setOrId(Integer orId) {
        this.orId = orId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water.wat_state
     *
     * @return the value of water.wat_state
     *
     * @mbg.generated
     */
    public Integer getWatState() {
        return watState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water.wat_state
     *
     * @param watState the value for water.wat_state
     *
     * @mbg.generated
     */
    public void setWatState(Integer watState) {
        this.watState = watState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", watId=").append(watId);
        sb.append(", watMoney=").append(watMoney);
        sb.append(", watDate=").append(watDate);
        sb.append(", orId=").append(orId);
        sb.append(", watState=").append(watState);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}