package com.aaa.dao;

import com.aaa.entity.Water;
import java.util.List;

public interface WaterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer watId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water
     *
     * @mbg.generated
     */
    int insert(Water record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water
     *
     * @mbg.generated
     */
    Water selectByPrimaryKey(Integer watId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water
     *
     * @mbg.generated
     */
    List<Water> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Water record);
}